### ISSUE TITLE
About wright npm package

### ISSUE THREAD

**Issue by porsager** [laosb/wright#1]
Hi.

Sorry, but I wasn't able to reply to your email (got a message not delivered email back). So I'll just answer here ;)

I'm sorry, but yes, we have a module we're still testing internally before public release, so yes we do plan to use the name, and hope to publish within the next month or two.

Greetings
Rasmus Porsager

**Comment by laosb** [comment]
Hi @porsager,

I'm really sorry for troubling you about it, and I decided to use `wright-*` for this project (for now, only `wright-core` used). Hope this won't affect your package naming! Thank you for your reply.
